[phases.setup]
nixPkgs = ["zbar", "libzbar", "zxing-cpp", "mupdf", "mupdf-tools", "gcc", "libstdcxx5"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -m app.main"
